# Generated by Django 2.2.24 on 2022-09-12 04:18

from django.db import migrations

def filling_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [migrations.RunPython(filling_new_building)
    ]
