# Generated by Django 2.2.24 on 2022-09-14 03:47

from django.db import migrations
from django.contrib.auth.models import User


def filling_liked_by(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        for user in User.objects.all():
            flat.liked_by.add(user.id)
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_liked_by'),
    ]

    operations = [migrations.RunPython(filling_liked_by)
    ]
