# Generated by Django 2.2.24 on 2022-09-15 03:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220915_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='+79803004820', max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
