# Generated by Django 2.2.24 on 2022-09-15 04:45

from django.db import migrations
import phonenumbers


def filling_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        try:
            owners_phonenumber = phonenumbers.parse(flat.owners_phonenumber, "RU")
            if phonenumbers.is_valid_number(owners_phonenumber):
                flat.owner_pure_phone = phonenumbers.format_number(owners_phonenumber,
                                                            phonenumbers.PhoneNumberFormat.INTERNATIONAL)
                flat.save()
        except phonenumbers.phonenumberutil.NumberParseException:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220915_0701'),

    ]

    operations = [migrations.RunPython(filling_owner_pure_phone)
    ]
