# Generated by Django 2.2.24 on 2022-09-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='address',
            new_name='flat',
        ),
    ]
