# Generated by Django 2.2.24 on 2022-09-17 05:42

from django.db import migrations


def create_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner,
                                    owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone,
                                    )



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20220917_0841'),
    ]

    operations = [migrations.RunPython(create_owners)
    ]
