# Generated by Django 2.2.24 on 2022-09-17 10:10

from django.db import migrations

def filling_owner_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all().iterator():
        flats = Flat.objects.filter(owner=owner.owner)
        owner.flat.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20220917_1309'),
    ]

    operations = [migrations.RunPython(filling_owner_flat)
    ]

