# Generated by Django 2.2.24 on 2022-09-18 05:51

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20220917_1310'),
    ]

    operations = [migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        )
    ]
