# Generated by Django 2.2.24 on 2022-09-18 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0021_auto_20220918_0851'),
    ]

    operations = [migrations.RemoveField(
        model_name='flat',
        name='owner',
    ), migrations.RemoveField(
        model_name='flat',
        name='owners_phonenumber',
    )
    ]
