# Generated by Django 2.2.24 on 2022-09-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_auto_20220927_1022'),
    ]

    operations = [migrations.RemoveField(
        model_name='flat',
        name='liked_by'
        )
    ]
